# Singular Value Decomposition


## Apa itu SVD

SVD (Singular Value Decomposition) adalah dekomposisi matriks yang sangat penting dalam aljabar linear, statistik, dan pembelajaran mesin. SVD memecah sebuah matriks menjadi tiga komponen dasar yang mengungkap struktur internal dari data tersebut.


SVD adalah metode untuk membagi sebuah matriks menjadi tiga matriks:

$$
A = U \Sigma V^T
$$

Dimana:

* $A$ adalah matriks asli berukuran $m \times n$
* $U$ adalah matriks ortogonal berukuran $m \times m$
* $\Sigma$ adalah matriks diagonal berukuran $m \times n$ (isi diagonalnya adalah singular values ≥ 0)
* $V^T$ adalah transpose dari matriks ortogonal $V$ berukuran $n \times n$



## Kegunaan SVD

1. Reduksi Dimensi (Dimensionality Reduction)

   * Digunakan dalam teknik seperti PCA (Principal Component Analysis) untuk mengurangi kompleksitas data.

2. Sistem Rekomendasi

   * Misalnya pada Netflix, Spotify, SVD digunakan dalam collaborative filtering untuk merekomendasikan item.

3. Pengolahan Citra

   * Mengkompres gambar dengan menyimpan sebagian nilai singular terbesar.

4. Solusi untuk Sistem Persamaan Linear

   * Menyelesaikan sistem linear yang tidak dapat diselesaikan dengan metode biasa.

5. Pendeteksian Noise dan Filtering

   * Menyaring komponen yang tidak penting dari data.



## Formula SVD

Misalkan $A$ adalah matriks $m \times n$, maka:

$$
A = U \Sigma V^T
$$

* $U =$ eigenvector dari $AA^T$
* $V =$ eigenvector dari $A^TA$
* Singular values $\sigma_i$ adalah akar dari eigenvalue $\lambda_i$ dari $A^TA$ atau $AA^T$:

  $$
  \sigma_i = \sqrt{\lambda_i}
  $$
* $\Sigma$ adalah matriks diagonal yang berisi $\sigma_1, \sigma_2, ..., \sigma_r$ di diagonal utama (dengan $r =$ rank dari $A$)



### Contoh Sederhana

Misal matriks $A$:

$$
A = \begin{bmatrix}
3 & 1 \\
1 & 3
\end{bmatrix}
$$

Dengan SVD, kita dapat menuliskannya sebagai:

$$
A = U \Sigma V^T
$$

Hasil perhitungan (dengan alat bantu):

$$
U = \begin{bmatrix}
\frac{1}{\sqrt{2}} & -\frac{1}{\sqrt{2}} \\
\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}} \\
\end{bmatrix}, \quad
\Sigma = \begin{bmatrix}
4 & 0 \\
0 & 2 \\
\end{bmatrix}, \quad
V^T = \begin{bmatrix}
\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}} \\
-\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}} \\
\end{bmatrix}
$$




###  Contoh Matriks 2X2

Misalkan matriks:

$$
A = \begin{bmatrix}
3 & 1 \\
1 & 3
\end{bmatrix}
$$

### 1. Hitung $A^TA$ dan $AA^T$

$$
A^T A = \begin{bmatrix}
3 & 1 \\
1 & 3
\end{bmatrix}^T
\begin{bmatrix}
3 & 1 \\
1 & 3
\end{bmatrix}
= \begin{bmatrix}
10 & 6 \\
6 & 10
\end{bmatrix}
$$

$$
AA^T = A A^T = \begin{bmatrix}
10 & 6 \\
6 & 10
\end{bmatrix}
$$

### 2. Cari eigenvalue dari $A^TA$

$$
\text{det}(A^TA - \lambda I) = 0
\Rightarrow \text{det}
\begin{bmatrix}
10 - \lambda & 6 \\
6 & 10 - \lambda
\end{bmatrix} = 0
$$

$$
(10 - \lambda)^2 - 36 = 0
\Rightarrow \lambda = 16, 4
$$

### 3. Cari eigenvector $v_1, v_2$ dari $A^TA$

Untuk $\lambda = 16$:

$$
(A^TA - 16I)v = 0
\Rightarrow \begin{bmatrix}
-6 & 6 \\
6 & -6
\end{bmatrix}
\Rightarrow v_1 = \frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ 1 \end{bmatrix}
$$

Untuk $\lambda = 4$:

$$
v_2 = \frac{1}{\sqrt{2}} \begin{bmatrix} -1 \\ 1 \end{bmatrix}
$$

Maka:

$$
V = \begin{bmatrix}
\frac{1}{\sqrt{2}} & -\frac{1}{\sqrt{2}} \\
\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}}
\end{bmatrix}, \quad V^T = V^\top
$$

### 4. Hitung Singular Value

$$
\sigma_1 = \sqrt{16} = 4,\quad \sigma_2 = \sqrt{4} = 2
\Rightarrow \Sigma = \begin{bmatrix}
4 & 0 \\
0 & 2
\end{bmatrix}
$$

### 5. Hitung $U$

Gunakan:

$$
u_i = \frac{1}{\sigma_i} A v_i
$$

Contoh:

$$
u_1 = \frac{1}{4} A \cdot v_1 = \frac{1}{4} \cdot A \cdot \frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ 1 \end{bmatrix}
= \frac{1}{4\sqrt{2}} \cdot \begin{bmatrix} 4 \\ 4 \end{bmatrix}
= \frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ 1 \end{bmatrix}
$$

$$
u_2 = \frac{1}{2} A \cdot v_2 = \frac{1}{2\sqrt{2}} \cdot \begin{bmatrix} 2 \\ -2 \end{bmatrix}
= \frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ -1 \end{bmatrix}
$$

Maka:

$$
U = \begin{bmatrix}
\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}} \\
\frac{1}{\sqrt{2}} & -\frac{1}{\sqrt{2}}
\end{bmatrix}
$$



In [ ]:
import numpy as np

# Matriks A
A = np.array([
    [3, 1],
    [1, 3]
])

# 1. Hitung A^T A dan AA^T
ATA = A.T @ A
AAT = A @ A.T

# 2. Eigenvalue dan eigenvector dari A^T A
eigvals, eigvecs = np.linalg.eig(ATA)

# Urutkan eigenvalue dari besar ke kecil
idx = np.argsort(eigvals)[::-1]
eigvals_sorted = eigvals[idx]
eigvecs_sorted = eigvecs[:, idx]

# 3. Matriks V dan V^T
V = eigvecs_sorted
V_T = V.T

# 4. Singular values (akar dari eigenvalue)
singular_values = np.sqrt(eigvals_sorted)
Sigma = np.diag(singular_values)

# 5. Hitung U = (1/σ_i) A v_i
U = np.zeros_like(A, dtype=np.float64)
for i in range(2):
    vi = V[:, i]
    ui = A @ vi / singular_values[i]
    U[:, i] = ui

# 6. Verifikasi rekonstruksi A
A_reconstructed = U @ Sigma @ V_T

# 7. Tampilkan hasil
np.set_printoptions(precision=4, suppress=True)
print("A:")
print(A)
print("\nA^T A:")
print(ATA)
print("\nEigenvalues (sorted):")
print(eigvals_sorted)
print("\nV (right singular vectors):")
print(V)
print("\nV^T:")
print(V_T)
print("\nSingular values (Sigma):")
print(Sigma)
print("\nU (left singular vectors):")
print(U)
print("\nA reconstructed from SVD:")
print(A_reconstructed)

A:
[[3 1]
 [1 3]]

A^T A:
[[10  6]
 [ 6 10]]

Eigenvalues (sorted):
[16.  4.]

V (right singular vectors):
[[ 0.7071 -0.7071]
 [ 0.7071  0.7071]]

V^T:
[[ 0.7071  0.7071]
 [-0.7071  0.7071]]

Singular values (Sigma):
[[4. 0.]
 [0. 2.]]

U (left singular vectors):
[[ 0.7071 -0.7071]
 [ 0.7071  0.7071]]

A reconstructed from SVD:
[[3. 1.]
 [1. 3.]]


### Contoh Matriks 3x2



Diberikan matriks:

$$
A = \begin{bmatrix}
4 & 1 \\
2 & 7 \\
1 & 4
\end{bmatrix}
$$

### 1. Perhitungan Eigenvalue dan Eigenvector dari $A^T A$

- Langkah 1: Transpose Matriks $A$

$$
A^T = \begin{bmatrix}
4 & 2 & 1 \\
1 & 7 & 4
\end{bmatrix}
$$

- Langkah 2: Hitung $A^T A$

$$
A^T A =
\begin{bmatrix}
4 & 2 & 1 \\
1 & 7 & 4
\end{bmatrix}
\cdot
\begin{bmatrix}
4 & 1 \\
2 & 7 \\
1 & 4
\end{bmatrix}
=
\begin{bmatrix}
21 & 22 \\
22 & 66
\end{bmatrix}
$$

- Langkah 3: Eigenvalue

Mencari $\lambda$ dari:

$$
\det(A^T A - \lambda I) = 0
$$

$$
\left|
\begin{array}{cc}
21 - \lambda & 22 \\
22 & 66 - \lambda
\end{array}
\right| = 0
$$

Hasilnya:

$$
\lambda_1 \approx 74.97, \quad \lambda_2 \approx 12.03
$$

- Langkah 4: Eigenvector

Eigenvector yang sesuai (sudah dinormalisasi):

$$
V = \begin{bmatrix}
-0.9200 & -0.3775 \\
0.3775 & -0.9260
\end{bmatrix}
$$

### 2. Dekomposisi Matriks (Spektral)

Karena $A^T A$ simetris, maka dapat ditulis:

$$
A^T A = V \Lambda V^T
$$

dengan:

$$
\Lambda = \begin{bmatrix}
74.97 & 0 \\
0 & 12.03
\end{bmatrix}
$$

- 3. Singular Value Decomposition (SVD)

Dekomposisi SVD dari $A$:

$$
A = U \Sigma V^T
$$

- a. Matriks $\Sigma$ (Singular Values)

Singular values adalah akar dari eigenvalue:

$$
\sigma_1 = \sqrt{74.97} \approx 8.898, \quad \sigma_2 = \sqrt{12.03} \approx 3.469
$$

$$
\Sigma = \begin{bmatrix}
8.898 & 0 \\
0 & 3.469 \\
0 & 0
\end{bmatrix}
$$

- b. Matriks $V^T$

$$
V^T = \begin{bmatrix}
-0.3775 & -0.9260 \\
0.9280 & -0.3775
\end{bmatrix}
$$

- c. Matriks $U$

Diperoleh dari perhitungan:

$$
u_i = \frac{1}{\sigma_i} A v_i
$$

Hasil akhir:

$$
U = \begin{bmatrix}
-0.2813 & 0.9580 & 0.0333 \\
-0.8389 & -0.2279 & -0.4924 \\
-0.4714 & -0.1083 & 0.8657
\end{bmatrix}
$$


In [ ]:
import numpy as np
from numpy.linalg import eig

# Matriks A (3x2)
A = np.array([
    [4, 1],
    [2, 7],
    [1, 4]
])

# Step 1: Hitung A^T A
ATA = A.T @ A

# Step 2: Hitung eigenvalue dan eigenvector dari A^T A
eigvals, eigvecs = eig(ATA)

# Step 3: Urutkan eigenvalue dari besar ke kecil
idx = np.argsort(eigvals)[::-1]
eigvals_sorted = eigvals[idx]
eigvecs_sorted = eigvecs[:, idx]

# Step 4: Matriks Lambda (eigenvalue diagonal)
Lambda = np.diag(eigvals_sorted)

# Step 5: Matriks V dan V^T
V = eigvecs_sorted
V_T = V.T

# Step 6: Matriks Sigma = akar dari eigenvalue
singular_values = np.sqrt(eigvals_sorted)
Sigma = np.zeros((3, 2))
np.fill_diagonal(Sigma, singular_values)

# Step 7: Hitung U = (1/σ_i) A v_i
U = np.zeros((3, 3))
for i in range(2):
    vi = V[:, i]
    ui = A @ vi / singular_values[i]
    U[:, i] = ui

# Step 8: Lengkapi U dengan kolom ke-3 ortonormal (gunakan cross product)
u1 = U[:, 0]
u2 = U[:, 1]
u3 = np.cross(u1, u2)
U[:, 2] = u3 / np.linalg.norm(u3)

# Step 9: Rekonstruksi A
A_reconstructed = U @ Sigma @ V_T

# Cetak hasil
np.set_printoptions(precision=4, suppress=True)
print("Matriks A:")
print(A)
print("\nMatriks A^T A:")
print(ATA)
print("\nEigenvalues (sorted):")
print(eigvals_sorted)
print("\nLambda:")
print(Lambda)
print("\nV (eigenvector A^T A):")
print(V)
print("\nV^T:")
print(V_T)
print("\nSigma:")
print(Sigma)
print("\nU:")
print(U)
print("\nA Reconstructed:")
print(A_reconstructed)

Matriks A:
[[4 1]
 [2 7]
 [1 4]]

Matriks A^T A:
[[21 22]
 [22 66]]

Eigenvalues (sorted):
[74.9682 12.0318]

Lambda:
[[74.9682  0.    ]
 [ 0.     12.0318]]

V (eigenvector A^T A):
[[-0.3775 -0.926 ]
 [-0.926   0.3775]]

V^T:
[[-0.3775 -0.926 ]
 [-0.926   0.3775]]

Sigma:
[[8.6584 0.    ]
 [0.     3.4687]
 [0.     0.    ]]

U:
[[-0.2813 -0.959  -0.0333]
 [-0.8358  0.2279  0.4994]
 [-0.4714  0.1683 -0.8657]]

A Reconstructed:
[[4. 1.]
 [2. 7.]
 [1. 4.]]
